### ISSUE TITLE
Does this have function to compute the loss, i.e. the Wasserstein distance

### ISSUE THREAD

**Issue by bearinsuke** [zsteve/wtf#1]
Hi,

It is much appreciated for your work! However, I have a small question, is there a function in WTF that can compute the Wasserstein distance between 2 tensors in this code? If not, how can I achieve this function?

Thank you very much!

**Comment by zsteve** [comment]
Hi @bearinsuke , 
Sorry for the slow response as for some reason I haven't been receiving any notifications from GitHub. 
In the method proposed by this paper/code, the factorization problem is solved blockwise, with each block being a smooth convex program that is solved via the dual. As a result I don't think I implemented a function to calculate the primal distance between two arbitrary tensors.
Depending on how you want to define the distance between two tensors, however, you can achieve this quite straightforwardly:
- If you treat the tensor as a prob. distribution supported on an n-dimensional grid, you can directly implement Sinkhorn iterations with a factorized Gibbs kernel (see the supplementary material of the accompanying paper to this repo).
- Alternatively if each slice is a different distribution, you could directly compute the distance using PythonOT functionality.
Hope that helps!

**Comment by bearinsuke** [comment]
Hi Stephen,
Thank you very much for the response. I do also have some questions about this work. I want to contact you via email and close this issue.
Thanks again.
